import{a as g,i as n,S as f}from"./assets/vendor-tnUJPedx.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))d(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const a={form:document.querySelector(".search-form"),input:document.querySelector('input[name="searchQuery"]'),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more")};function u(e,t=!1){const r=e.map(h).join("");t?a.gallery.insertAdjacentHTML("beforeend",r):a.gallery.innerHTML=r}function h(e){return`
    <div class="photo-card">
        <a class="card-link" href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
            <p class="info-item"><b>Likes</b> <span>${e.likes}</span></p>
            <p class="info-item"><b>Views</b> <span>${e.views}</span></p>
            <p class="info-item"><b>Comments</b> <span>${e.comments}</span></p>
            <p class="info-item"><b>Downloads</b> <span>${e.downloads}</span></p>
        </div>
    </div>`}const y="47870617-7ec65d65554e9e3e1b4aa2202",L="https://pixabay.com/api/";async function p(e,t){a.loader.classList.remove("hidden"),a.loadMore.classList.add("hidden");try{return(await g.get(L,{params:{key:y,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(r){throw console.error("❌ Error fetching data:",r),r}finally{a.loader.classList.add("hidden")}}let l=null,i=null;a.form.addEventListener("submit",async e=>{if(e.preventDefault(),l=a.input.value.trim(),i=1,!l){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight",timeout:3e3});return}a.gallery.innerHTML="";try{const t=await p(l,i),r=t.hits;if(console.log(t),!r||r.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",timeout:3e3});return}u(r),m.refresh(),a.loadMore.classList.remove("hidden")}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight",timeout:3e3})}});const m=new f(".gallery a",{captionsData:"alt",captionDelay:250,animationSpeed:300,enableKeyboard:!0});a.loadMore.addEventListener("click",b);async function b(e){i+=1,e.preventDefault(),a.loadMore.classList.add("hidden");try{const t=await p(l,i),r=t.hits;if(!r||r.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",timeout:3e3});return}u(r,!0),m.refresh(),w(),a.loadMore.classList.remove("hidden"),i*15>=t.totalHits&&(a.loadMore.classList.add("hidden"),n.warning({title:"Warning",message:"We`re sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3}))}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight",timeout:3e3})}}function w(){const{height:e}=document.querySelector(".photo-card").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
